export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser, fetchTicketsByRange } from "@/lib/jira";
import { loadTasks } from "@/lib/taskStoreServer";
import { loadMilestones } from "@/lib/milestoneStore";
import { loadProfDev } from "@/lib/profDevStore";
import { loadSummaries } from "@/lib/summaryStore";
import { loadTopicStats } from "@/lib/growthStore";
import { callGemini } from "@/lib/summarize";
import { savePerformanceEntry } from "@/lib/performanceStore";
import {
  format,
  startOfWeek,
  endOfWeek,
  subWeeks,
  startOfMonth,
  endOfMonth,
  subMonths,
  startOfQuarter,
  endOfQuarter,
  subQuarters,
} from "date-fns";

// ─── Slack formatter ──────────────────────────────────────────────────────────

const SECTION_ICONS: Record<string, string> = {
  "Time Management": "⏱",
  "Delivery & Efficiency": "🚀",
  "Leadership & Collaboration": "🤝",
  "Communication & Influence": "💬",
  "Professional Growth": "📈",
  "Key Recommendations": "✅",
};

function insightsToSlack(insights: string, rangeLabel: string, userName: string): string {
  const lines: string[] = [
    `*📊 Performance Insights — ${userName} — ${rangeLabel}*`,
    `_Generated by Clock-It · ${format(new Date(), "EEEE, MMMM d yyyy")}_`,
    "",
    "━━━━━━━━━━━━━━━━━━━━",
  ];

  // Split on ## headings
  const sections = insights.split(/\n(?=##\s)/);
  for (const block of sections) {
    const match = block.match(/^##\s+(.+)\n?([\s\S]*)/);
    if (!match) continue;

    const title = match[1].trim();
    const body = match[2].trim();
    const icon = SECTION_ICONS[title] ?? "•";

    lines.push(`\n*${icon} ${title}*`);

    // For Key Recommendations, render numbered list items
    if (title.toLowerCase().includes("recommendation")) {
      const items = body.split(/\n/).filter((l) => /^\d+[\.\)]/.test(l.trim()));
      if (items.length > 0) {
        for (const item of items) {
          lines.push(`  • ${item.replace(/^\d+[\.\)]\s*/, "")}`);
        }
      } else {
        lines.push(body);
      }
    } else {
      lines.push(body);
    }

    lines.push("━━━━━━━━━━━━━━━━━━━━");
  }

  lines.push("", "_Automated by Clock-It Performance Hub_");
  return lines.join("\n");
}

// ─── Date range from frequency ────────────────────────────────────────────────

type Frequency = "weekly" | "monthly" | "quarterly";

function rangeFromFrequency(freq: Frequency): { startDate: string; endDate: string; rangeLabel: string } {
  const today = new Date();
  const fmt = (d: Date) => format(d, "yyyy-MM-dd");

  switch (freq) {
    case "weekly": {
      const lastWeek = subWeeks(today, 1);
      return {
        startDate: fmt(startOfWeek(lastWeek, { weekStartsOn: 1 })),
        endDate: fmt(endOfWeek(lastWeek, { weekStartsOn: 1 })),
        rangeLabel: `Last Week (w/c ${fmt(startOfWeek(lastWeek, { weekStartsOn: 1 }))})`,
      };
    }
    case "monthly": {
      const lastMonth = subMonths(today, 1);
      return {
        startDate: fmt(startOfMonth(lastMonth)),
        endDate: fmt(endOfMonth(lastMonth)),
        rangeLabel: format(lastMonth, "MMMM yyyy"),
      };
    }
    case "quarterly": {
      const lastQ = subQuarters(today, 1);
      const qStart = startOfQuarter(lastQ);
      const qEnd = endOfQuarter(lastQ);
      const qNum = Math.floor(qStart.getMonth() / 3) + 1;
      return {
        startDate: fmt(qStart),
        endDate: fmt(qEnd),
        rangeLabel: `Q${qNum} ${qStart.getFullYear()}`,
      };
    }
  }
}

// ─── Core: generate + send ────────────────────────────────────────────────────

async function generateAndSend(
  startDate: string,
  endDate: string,
  rangeLabel: string,
  webhookUrl: string
): Promise<{ ok: boolean; message: string }> {
  // Fetch data
  let user = { displayName: "Team Member" };
  let tickets: Awaited<ReturnType<typeof fetchTicketsByRange>> = [];
  try {
    const jiraUser = await getCurrentUser();
    user = jiraUser;
    tickets = await fetchTicketsByRange(jiraUser.accountId, startDate, endDate);
  } catch {}

  const allTasks = await loadTasks();
  const milestones = await loadMilestones();
  const allProfDev = await loadProfDev();
  const topicStats = await loadTopicStats().catch(() => []);
  const filteredProfDev = allProfDev.filter(
    (e) => e.completedDate >= startDate && e.completedDate <= endDate
  );
  const summaries = await loadSummaries();

  const done = tickets.filter((t) => ["done", "closed", "resolved"].some((s) => t.status.toLowerCase().includes(s)));
  const inProgress = tickets.filter((t) => t.status.toLowerCase().includes("progress"));
  const inReview = tickets.filter((t) => t.status.toLowerCase().includes("review") || t.status.toLowerCase().includes("testing"));
  const todo = tickets.filter((t) => ["to do", "todo", "open", "backlog"].some((s) => t.status.toLowerCase() === s));

  const stats = {
    jiraTotal: tickets.length,
    jiraDone: done.length,
    jiraInProgress: inProgress.length,
    jiraInReview: inReview.length,
    jiraTodo: todo.length,
    jiraHours: tickets.reduce((s, t) => s + t.hours, 0),
    completionRate: tickets.length > 0 ? Math.round((done.length / tickets.length) * 100) : 0,
    meetingTasksDone: allTasks.filter((t) => t.status === "done").length,
    meetingTasksActive: allTasks.filter((t) => t.status === "in-progress").length,
    meetingTasksTotal: allTasks.length,
    milestonesCompleted: milestones.filter((m) => m.status === "completed").length,
    milestonesInProgress: milestones.filter((m) => m.status === "in-progress").length,
    milestonesTotal: milestones.length,
    profDevCount: filteredProfDev.length,
    profDevHours: filteredProfDev.reduce((s, e) => s + (e.durationHours ?? 0), 0),
    meetingsCount: summaries.length,
  };

  // Communication evidence
  const allContributions = summaries.flatMap((s) => s.summary.contributions ?? []).filter(Boolean);
  const allDecisions = summaries.flatMap((s) => s.summary.decisions ?? []).filter(Boolean);
  const allActionItems = summaries.flatMap((s) => s.summary.actionItems ?? []).filter((a) => a && a !== "No action items detected.");
  const sampleContribs = allContributions.slice(0, 5);

  const communicationSection = allContributions.length > 0
    ? `\n\nCommunication Evidence (from meeting transcripts):
- Meetings with recorded contributions: ${summaries.length}
- Total contributions: ${allContributions.length}
- Decisions involved in: ${allDecisions.length}
- Action items taken: ${allActionItems.length}
- Sample contributions:
${sampleContribs.map((c, i) => `  ${i + 1}. "${c}"`).join("\n")}`
    : "";

  const quizSection = topicStats.length > 0
    ? `\n\nProfessional Growth Quiz Performance (all-time):
- Topics tracked: ${topicStats.length}
- Overall avg score: ${Math.round(topicStats.reduce((s, t) => s + t.avgScore, 0) / topicStats.length)}%
- Best topic: ${topicStats.reduce((b, t) => t.avgScore > b.avgScore ? t : b).label} (${topicStats.reduce((b, t) => t.avgScore > b.avgScore ? t : b).avgScore}%)
- Weakest topic: ${topicStats[0].label} (${topicStats[0].avgScore}%)
- Total quiz sessions: ${topicStats.reduce((s, t) => s + t.attemptCount, 0)}`
    : "";

  const prompt = `You are a performance coach assessing a Senior Associate at a technology consulting/software company. For the period ${rangeLabel}, provide a structured performance summary with exactly these sections in order: ## Time Management, ## Delivery & Efficiency, ## Leadership & Collaboration, ## Communication & Influence, ## Professional Growth, ## Key Recommendations. Reference actual numbers. Be candid but constructive. 3-5 sentences per section.

Data for ${rangeLabel}:
- Jira tickets: ${stats.jiraTotal} total, ${stats.jiraDone} done (${stats.completionRate}%), ${stats.jiraInProgress} in progress, ${stats.jiraInReview} in review, ${stats.jiraTodo} todo
- Estimated Jira hours: ${stats.jiraHours}h
- Meeting tasks: ${stats.meetingTasksDone} done, ${stats.meetingTasksActive} active of ${stats.meetingTasksTotal} total
- Meetings attended: ${stats.meetingsCount}
- Milestones: ${stats.milestonesCompleted}/${stats.milestonesTotal} done, ${stats.milestonesInProgress} in progress
- Professional development: ${stats.profDevCount} activities, ${stats.profDevHours}h${communicationSection}${quizSection}`;

  let insights: string;
  try {
    insights = await callGemini(prompt);
  } catch {
    insights = [
      `## Time Management\nLogged work across ${stats.jiraTotal} Jira tickets this period. No timer session data available for automated reports.`,
      `## Delivery & Efficiency\n${stats.jiraDone} of ${stats.jiraTotal} tickets completed (${stats.completionRate}%). ${stats.jiraInProgress} in progress, ${stats.jiraInReview} in review.`,
      `## Leadership & Collaboration\nAttended ${stats.meetingsCount} meetings. ${stats.meetingTasksDone} meeting tasks completed of ${stats.meetingTasksTotal} total.`,
      `## Communication & Influence\nContributions captured across ${summaries.length} meeting summaries. Review your contributions for depth and strategic framing.`,
      `## Professional Growth\n${stats.profDevCount} professional development activities (${stats.profDevHours}h). Milestones: ${stats.milestonesCompleted}/${stats.milestonesTotal} completed.`,
      `## Key Recommendations\n1. Close ${stats.jiraInProgress} in-progress tickets.\n2. Address ${stats.jiraTodo} backlog items.\n3. Maintain professional development momentum.`,
    ].join("\n\n");
  }

  // Auto-save to history
  const autoLabel = `${rangeLabel} — auto`;
  await savePerformanceEntry({
    dateLabel: autoLabel,
    rangeLabel,
    startDate,
    endDate,
    stats: stats as Record<string, number | string>,
    insights,
  });

  // Send to Slack
  const slackText = insightsToSlack(insights, rangeLabel, user.displayName);
  const res = await fetch(webhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text: slackText, unfurl_links: false }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Slack error ${res.status}: ${body}`);
  }

  return { ok: true, message: `Performance insights for ${rangeLabel} sent to Slack.` };
}

// ─── POST — manual send (pass pre-generated insights text) ───────────────────

export async function POST(request: NextRequest) {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl || webhookUrl.includes("placeholder")) {
    return NextResponse.json({ error: "SLACK_WEBHOOK_URL is not configured." }, { status: 500 });
  }

  try {
    const body = await request.json();
    const { insights, rangeLabel, startDate, endDate } = body;

    if (insights && rangeLabel) {
      // Manual send — use pre-generated insights from the page
      let userName = "Team Member";
      try { userName = (await getCurrentUser()).displayName; } catch {}

      const slackText = insightsToSlack(insights, rangeLabel, userName);
      const res = await fetch(webhookUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: slackText, unfurl_links: false }),
      });
      if (!res.ok) throw new Error(`Slack error: ${res.status}`);
      return NextResponse.json({ ok: true });
    }

    // Full regenerate + send (if no pre-generated insights passed)
    if (!startDate || !endDate || !rangeLabel) {
      return NextResponse.json({ error: "insights+rangeLabel or startDate+endDate+rangeLabel required" }, { status: 400 });
    }
    const result = await generateAndSend(startDate, endDate, rangeLabel, webhookUrl);
    return NextResponse.json(result);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("[/api/performance/slack POST]", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

// ─── GET — cron trigger (?frequency=weekly|monthly|quarterly) ─────────────────

export async function GET(request: NextRequest) {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl || webhookUrl.includes("placeholder")) {
    return NextResponse.json({ error: "SLACK_WEBHOOK_URL is not configured." }, { status: 500 });
  }

  const freq = (request.nextUrl.searchParams.get("frequency") ?? "monthly") as Frequency;
  if (!["weekly", "monthly", "quarterly"].includes(freq)) {
    return NextResponse.json({ error: "frequency must be weekly, monthly, or quarterly" }, { status: 400 });
  }

  try {
    const { startDate, endDate, rangeLabel } = rangeFromFrequency(freq);
    const result = await generateAndSend(startDate, endDate, rangeLabel, webhookUrl);
    return NextResponse.json(result);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("[/api/performance/slack GET]", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
